In [2]:
import numpy as np

In [4]:
class Node(object):
    def __init__(self, data):
        self.data = data
        self.children = []
    
    def add_child(self, obj):
        self.children.append(obj)
    
def split(arr, cond):
  return [arr[cond], arr[~cond]]

In [6]:
## Test dataset
kd_test = [[3,1,4], [2,4,5], [5,2,3], [2,3,7], [1,7,4], [4,1,4], [7,3,4], [3,1,2], [5,1,5]]
kd_test

[[3, 1, 4],
 [2, 4, 5],
 [5, 2, 3],
 [2, 3, 7],
 [1, 7, 4],
 [4, 1, 4],
 [7, 3, 4],
 [3, 1, 2],
 [5, 1, 5]]

### Order of operations
- Sort data according to element 0
- Identify median point according to element 0 (this is the root node)
- Partition data on either side of median
- For each partition, sort according to element 1
- For each partition, find median point according to element 1 --> these are the two children nodes of the root node
- Partition each sub-partition on either side of median
- Etc.

In [ ]:
num_features = len(kd_test[0])
num_features = range(0, num_features) # Create list of number of 
tree = [] # Initialize kdTree

def kdTree(data, element):
    '''
    data to build nodes of tree
    element to sort and divide on
    '''
    # Sort data
    data = sorted(data, key=lambda x: x[element])
    data = np.array(data) # make sure it's array format

    # Identify median of data
    midpoint = len(data)//2
    median = data[midpoint]

    # Remove median from data
    data = np.delete(data, midpoint, 0)

    # Create node with median point
    point = Node(median)

    # Split data into > median or < median
    left_half = split(data, data[:,0]<=median[0])[0]
    right_half = split(data, data[:,0]<=median[0])[1]
        
        

In [7]:
## Order points based on 1st coordinate
kd_test = sorted(kd_test, key=lambda x: x[0])
kd_test = np.array(kd_test)
print(kd_test)

# Identify median
midpoint = len(kd_test)//2
median = kd_test[midpoint]
print("Median point is: ", median)

# Remove median from data
kd_test = np.delete(kd_test, midpoint, 0)


## Build Tree
# 1) Root = median
root = Node(median)

# 2) Split data into > median or < median
left_half = split(kd_test, kd_test[:,0]<=median[0])[0]
right_half = split(kd_test, kd_test[:,0]<=median[0])[1]

## Sort the left partition by 2nd coordinate
left_half = sorted(left_half, key=lambda x: x[1])
left_half = np.array(left_half)
print(left_half)

# Identify median
midpoint = len(left_half)//2
median = left_half[midpoint]
print("Left Median point is: ", median)
child = Node(median)
root.add_child(child) # Add left partition median as new child of root

# Remove median from data
left_half = np.delete(left_half, midpoint, 0)


## Sort the right partition
right_half = sorted(right_half, key=lambda x: x[1])
right_half = np.array(right_half)
print(right_half)

# Identify median
midpoint = len(right_half)//2
median = right_half[midpoint]
print("Median point is: ", median)
child = Node(median)
root.add_child(child) # Add right partition median as new child of root

# Remove median from data
right_half = np.delete(right_half, midpoint, 0)

[[1 7 4]
 [2 4 5]
 [2 3 7]
 [3 1 4]
 [3 1 2]
 [4 1 4]
 [5 2 3]
 [5 1 5]
 [7 3 4]]
Median point is:  [3 1 2]


In [16]:
root.children

[array([2, 4, 5]), array([5, 2, 3])]